FROM python:3.11-slim
COPY pyproject.toml poetry.lock /app/
WORKDIR /app
RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-dev
COPY data_router /app/data_router
CMD ["uvicorn", "data_router.server:app", "--host", "0.0.0.0", "--port", "8000"]