# Use root/example as user/password credentials
version: '3.1'
name: realtime-airline-distributed-database
services:
  zookeeper:
    image: zookeeper
    restart: always
  # Uncomment the following lines to expose zookeeper on localhost
  #    ports:
  #      - "2181:2181"
  db:
    image: custom_mysql
    restart: always
    environment:
      MYSQL_PASSWORD: dsci551
      ZOOKEEPER_SERVERS: "zookeeper"
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - zookeeper
  data_router:
    image: data_router
    restart: always
    depends_on:
      - db
      - zookeeper
    environment:
      ZOOKEEPER_SERVERS: "zookeeper"
    ports:
      # the app exposes port 8000 on the container and we map it to 8090 on the host
      - "8090:8000"