FROM python:3.11-slim
COPY pyproject.toml poetry.lock /app/
WORKDIR /app
RUN pip install poetry
RUN poetry config virtualenvs.create false
RUN poetry install --no-dev
COPY flightradar_data_producer /app/flightradar_data_producer
RUN chmod +x /app/flightradar_data_producer/run.sh
# Run the run.sh bash script
CMD ["/bin/bash", "/app/flightradar_data_producer/run.sh"]