# Use root/example as user/password credentials
version: '3.1'
name: realtime-airline-distributed-database
services:
  zookeeper:
    image: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
  # Uncomment the following lines to expose zookeeper on localhost
  #    ports:
  #      - "2181:2181"
  db:
    image: custom_mysql
    restart: always
    environment:
      MYSQL_PASSWORD: dsci551
      ZOOKEEPER_SERVERS: "zookeeper"
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - zookeeper
  data_router:
    image: data_router
    restart: always
    depends_on:
      - db
      - zookeeper
    environment:
      ZOOKEEPER_SERVERS: "zookeeper"
      MYSQL_USER: root
      MYSQL_PASSWORD: dsci551
    ports:
      # the app exposes port 8000 on the container and we map it to 8090 on the host
      - "8090:8000"
  kafka:
    image: confluentinc/cp-kafka:latest
    #    ports:
    #      - "9092:9092"
    #      - "29092:29092"
    #      - "9999:9999"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  selenuim:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
  data_producer:
    image: data_producer
    restart: always
    depends_on:
      - kafka
      - selenuim
    environment:
      KAFKA_CONFIG: '{"bootstrap.servers": "kafka:9092"}'
      SELENIUM_DRIVER_URL: "http://selenuim:4444"